### ISSUE TITLE
kingPhilipCanOrderFineGreenSocks: `class` gets shown as `$class`

### ISSUE THREAD

**Issue by ento** [elmbridge/elm-basics#6]
![image](https://cloud.githubusercontent.com/assets/21108/19454217/2198e2ec-946d-11e6-9410-cbb5a0623b77.png)

because it's a [reserved JS keyword](https://github.com/elm-lang/elm-compiler/blob/36dbf23f9ee63068922500c5853c59d9e7f6d93b/src/Generate/JavaScript/Variable.hs#L179). (and toString doesn't change it back)

- wrap `toString` and replace "$class" with "class"?
- cut the taxonomy short: `orderFineGreenSocks`

**Comment by avh4** [comment]
This will be unnecessary if https://github.com/elmbridge/intro-to-elm-part-1/pull/9 gets merged.

**Comment by avh4** [comment]
Closing due to #9
